# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_collection', models.CharField(choices=[('dress', 'dress'), ('seremoni', 'seremoni'), ('skjorte', 'skjorte'), ('sko', 'sko'), ('smoking', 'smoking'), ('slips', 'slips'), ('mansjett', 'mansjett'), ('sloyfe', 'sloyfe')], max_length=20)),
                ('collection_content', models.TextField()),
                ('collection_image', models.FileField(upload_to='')),
            ],
        ),
    ]
