# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_color', models.CharField(choices=[('bla', 'blå')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='collection',
            name='type_of_collection',
            field=models.CharField(choices=[('dress', 'dress'), ('brudgom', 'brudgom'), ('skjorte', 'skjorte'), ('sko', 'sko'), ('smoking', 'smoking'), ('slips', 'slips'), ('mansjett', 'mansjett'), ('sloyfe', 'sloyfe')], max_length=20),
        ),
    ]
