# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20180202_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='product_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
