# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20180202_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_headline', models.CharField(max_length=100)),
                ('tip_image', models.FileField(upload_to='')),
                ('tip_content', models.TextField(max_length=3000)),
            ],
        ),
        migrations.AlterField(
            model_name='collection',
            name='type_of_collection',
            field=models.CharField(choices=[('dress', 'dress'), ('brudgom', 'brudgom'), ('skjorte', 'skjorte'), ('sko', 'sko'), ('smoking', 'smoking'), ('slips', 'slips'), ('mansjettknapper', 'mansjettknapper'), ('sløyfe', 'sløyfe'), ('stoff', 'stoff')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dress',
            name='product_type',
            field=models.CharField(choices=[('dress', 'dress'), ('brudgom', 'brudgom'), ('skjorte', 'skjorte'), ('sko', 'sko'), ('smoking', 'smoking'), ('slips', 'slips'), ('mansjettknapper', 'mansjettknapper'), ('sløyfe', 'sløyfe'), ('stoff', 'stoff')], max_length=20),
        ),
    ]
