# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20180203_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dress_Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_guide_headline', models.CharField(max_length=100)),
                ('dress_guide_image', models.FileField(upload_to='')),
                ('dress_guide_content', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Dressen_Sitte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dressen_sitte_headline', models.CharField(max_length=100)),
                ('dressen_sitte_image', models.FileField(upload_to='')),
                ('dressen_sitte_content', models.TextField(max_length=3000)),
            ],
        ),
    ]
