# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_dress_guide_dressen_sitte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, unique=True)),
                ('product_description', models.CharField(max_length=50)),
                ('product_content', models.TextField(max_length=5000)),
                ('product_type', models.CharField(choices=[('dress', 'dress'), ('brudgom', 'brudgom'), ('skjorte', 'skjorte'), ('sko', 'sko'), ('smoking', 'smoking'), ('slips', 'slips'), ('mansjettknapper', 'mansjettknapper'), ('sløyfe', 'sløyfe'), ('stoff', 'stoff')], max_length=20)),
                ('product_image', models.FileField(upload_to='')),
                ('product_gallery_content', models.TextField(max_length=150)),
                ('product_keyword', models.CharField(max_length=50)),
                ('product_color', models.CharField(choices=[('blå', 'blå'), ('grå', 'grå'), ('sort', 'sort'), ('ivory', 'ivory'), ('hvit', 'hvit'), ('brun', 'brun'), ('lilla', 'lilla'), ('rosa', 'rosa'), ('beige', 'beige'), ('grønn', 'grønn'), ('gul', 'gul'), ('rød', 'rød')], max_length=20)),
            ],
        ),
    ]
