# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20180203_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_image', models.FileField(upload_to='')),
                ('news_headline', models.CharField(max_length=100)),
            ],
        ),
    ]
